//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RDS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A 的本地化字符串。
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alert 的本地化字符串。
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B 的本地化字符串。
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlueColor 的本地化字符串。
        /// </summary>
        internal static string BlueColor {
            get {
                return ResourceManager.GetString("BlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlueColor2 的本地化字符串。
        /// </summary>
        internal static string BlueColor2 {
            get {
                return ResourceManager.GetString("BlueColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlueTransparent 的本地化字符串。
        /// </summary>
        internal static string BlueTransparent {
            get {
                return ResourceManager.GetString("BlueTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C 的本地化字符串。
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell 的本地化字符串。
        /// </summary>
        internal static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart_Name1 的本地化字符串。
        /// </summary>
        internal static string Chart_Name1 {
            get {
                return ResourceManager.GetString("Chart_Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart_Name2 的本地化字符串。
        /// </summary>
        internal static string Chart_Name2 {
            get {
                return ResourceManager.GetString("Chart_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart_Name3 的本地化字符串。
        /// </summary>
        internal static string Chart_Name3 {
            get {
                return ResourceManager.GetString("Chart_Name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart_Name4 的本地化字符串。
        /// </summary>
        internal static string Chart_Name4 {
            get {
                return ResourceManager.GetString("Chart_Name4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart_Name5 的本地化字符串。
        /// </summary>
        internal static string Chart_Name5 {
            get {
                return ResourceManager.GetString("Chart_Name5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart_Name6 的本地化字符串。
        /// </summary>
        internal static string Chart_Name6 {
            get {
                return ResourceManager.GetString("Chart_Name6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChartColor1 的本地化字符串。
        /// </summary>
        internal static string ChartColor1 {
            get {
                return ResourceManager.GetString("ChartColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChartColor2 的本地化字符串。
        /// </summary>
        internal static string ChartColor2 {
            get {
                return ResourceManager.GetString("ChartColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChartColor3 的本地化字符串。
        /// </summary>
        internal static string ChartColor3 {
            get {
                return ResourceManager.GetString("ChartColor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copies/mL 的本地化字符串。
        /// </summary>
        internal static string Copies {
            get {
                return ResourceManager.GetString("Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Csv 的本地化字符串。
        /// </summary>
        internal static string Csv {
            get {
                return ResourceManager.GetString("Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D 的本地化字符串。
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DatabaseConnectionString 的本地化字符串。
        /// </summary>
        internal static string DatabaseConnectionString {
            get {
                return ResourceManager.GetString("DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyyMMdd 的本地化字符串。
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy/MM/dd 的本地化字符串。
        /// </summary>
        internal static string DateFormat1 {
            get {
                return ResourceManager.GetString("DateFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyyMMddhhmmss 的本地化字符串。
        /// </summary>
        internal static string DateFormat2 {
            get {
                return ResourceManager.GetString("DateFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *.{0} 的本地化字符串。
        /// </summary>
        internal static string DefaultExt {
            get {
                return ResourceManager.GetString("DefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoubleLeft 的本地化字符串。
        /// </summary>
        internal static string DoubleLeft {
            get {
                return ResourceManager.GetString("DoubleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoubleRight 的本地化字符串。
        /// </summary>
        internal static string DoubleRight {
            get {
                return ResourceManager.GetString("DoubleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 00 的本地化字符串。
        /// </summary>
        internal static string DoubleZero {
            get {
                return ResourceManager.GetString("DoubleZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业定量质控品S 的本地化字符串。
        /// </summary>
        internal static string DynamicItemName1 {
            get {
                return ResourceManager.GetString("DynamicItemName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最低检出限参考品 的本地化字符串。
        /// </summary>
        internal static string DynamicItemName2 {
            get {
                return ResourceManager.GetString("DynamicItemName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灵敏度/定量参考品 的本地化字符串。
        /// </summary>
        internal static string DynamicItemName3 {
            get {
                return ResourceManager.GetString("DynamicItemName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #.#E+00 的本地化字符串。
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ● 的本地化字符串。
        /// </summary>
        internal static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from [{0}$] 的本地化字符串。
        /// </summary>
        internal static string ExcelCommandString {
            get {
                return ResourceManager.GetString("ExcelCommandString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provider=Microsoft.Jet.OLEDB.4.0;Data Source={0};Extended Properties=&apos;Excel 8.0;HDR=Yes;IMEX=1;&apos; 的本地化字符串。
        /// </summary>
        internal static string ExcelConnectionString {
            get {
                return ResourceManager.GetString("ExcelConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string ExperimentTypeNone {
            get {
                return ResourceManager.GetString("ExperimentTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpNo 的本地化字符串。
        /// </summary>
        internal static string ExpNo {
            get {
                return ResourceManager.GetString("ExpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Apps\Export 的本地化字符串。
        /// </summary>
        internal static string ExportFilePath {
            get {
                return ResourceManager.GetString("ExportFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fConc 的本地化字符串。
        /// </summary>
        internal static string fConc {
            get {
                return ResourceManager.GetString("fConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女性 的本地化字符串。
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 文件|*.{0} 的本地化字符串。
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalView_Message1 的本地化字符串。
        /// </summary>
        internal static string FinalView_Message1 {
            get {
                return ResourceManager.GetString("FinalView_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalView_Message2 的本地化字符串。
        /// </summary>
        internal static string FinalView_Message2 {
            get {
                return ResourceManager.GetString("FinalView_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FinalView_Message3 的本地化字符串。
        /// </summary>
        internal static string FinalView_Message3 {
            get {
                return ResourceManager.GetString("FinalView_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB2312 的本地化字符串。
        /// </summary>
        internal static string GB2312 {
            get {
                return ResourceManager.GetString("GB2312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GrayColor 的本地化字符串。
        /// </summary>
        internal static string GrayColor {
            get {
                return ResourceManager.GetString("GrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreenColor 的本地化字符串。
        /// </summary>
        internal static string GreenColor {
            get {
                return ResourceManager.GetString("GreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreenTransparent 的本地化字符串。
        /// </summary>
        internal static string GreenTransparent {
            get {
                return ResourceManager.GetString("GreenTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HBV 的本地化字符串。
        /// </summary>
        internal static string HBV {
            get {
                return ResourceManager.GetString("HBV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HCV 的本地化字符串。
        /// </summary>
        internal static string HCV {
            get {
                return ResourceManager.GetString("HCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Apps\Resource\Other\Help.xps 的本地化字符串。
        /// </summary>
        internal static string HelpFilePath {
            get {
                return ResourceManager.GetString("HelpFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HistroyView_SexItem_Both 的本地化字符串。
        /// </summary>
        internal static string HistroyView_SexItem_Both {
            get {
                return ResourceManager.GetString("HistroyView_SexItem_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HistroyView_SexItem_Man 的本地化字符串。
        /// </summary>
        internal static string HistroyView_SexItem_Man {
            get {
                return ResourceManager.GetString("HistroyView_SexItem_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HistroyView_SexItem_Woman 的本地化字符串。
        /// </summary>
        internal static string HistroyView_SexItem_Woman {
            get {
                return ResourceManager.GetString("HistroyView_SexItem_Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HIV 的本地化字符串。
        /// </summary>
        internal static string HIV {
            get {
                return ResourceManager.GetString("HIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message6 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message6 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message6_1 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message6_1 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message7 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message7 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message7_1 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message7_1 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message8 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message8 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message8_1 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message8_1 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message9 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message9 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InitializeSuppliesView_Message9_1 的本地化字符串。
        /// </summary>
        internal static string InitializeSuppliesView_Message9_1 {
            get {
                return ResourceManager.GetString("InitializeSuppliesView_Message9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InstrumentName 的本地化字符串。
        /// </summary>
        internal static string InstrumentName {
            get {
                return ResourceManager.GetString("InstrumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InstrumentType 的本地化字符串。
        /// </summary>
        internal static string InstrumentType {
            get {
                return ResourceManager.GetString("InstrumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InstrumentVersion 的本地化字符串。
        /// </summary>
        internal static string InstrumentVersion {
            get {
                return ResourceManager.GetString("InstrumentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IU/mL 的本地化字符串。
        /// </summary>
        internal static string IU {
            get {
                return ResourceManager.GetString("IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 jpg 的本地化字符串。
        /// </summary>
        internal static string Jpg {
            get {
                return ResourceManager.GetString("Jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Apps\Config.json 的本地化字符串。
        /// </summary>
        internal static string JsonConfigFilePath {
            get {
                return ResourceManager.GetString("JsonConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L_T_Ok 的本地化字符串。
        /// </summary>
        internal static string L_T_Ok {
            get {
                return ResourceManager.GetString("L_T_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /RDS;component/Apps/Dictionary/Language/{0}.xaml 的本地化字符串。
        /// </summary>
        internal static string LanguageFilePath {
            get {
                return ResourceManager.GetString("LanguageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LanguageInformation 的本地化字符串。
        /// </summary>
        internal static string LanguageInformation {
            get {
                return ResourceManager.GetString("LanguageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LanguagePath 的本地化字符串。
        /// </summary>
        internal static string LanguagePath {
            get {
                return ResourceManager.GetString("LanguagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Languages 的本地化字符串。
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}\Apps\LisFiles\Barcode_{1}.xml 的本地化字符串。
        /// </summary>
        internal static string LisFilesPath {
            get {
                return ResourceManager.GetString("LisFilesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strAge 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Age {
            get {
                return ResourceManager.GetString("LisInfo_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strBarcode 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Barcode {
            get {
                return ResourceManager.GetString("LisInfo_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strBirthday 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Birthday {
            get {
                return ResourceManager.GetString("LisInfo_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strDateTime 的本地化字符串。
        /// </summary>
        internal static string LisInfo_DateTime {
            get {
                return ResourceManager.GetString("LisInfo_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strItem 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Item {
            get {
                return ResourceManager.GetString("LisInfo_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strName 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Name {
            get {
                return ResourceManager.GetString("LisInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strSampleID 的本地化字符串。
        /// </summary>
        internal static string LisInfo_SampleID {
            get {
                return ResourceManager.GetString("LisInfo_SampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strSampleType 的本地化字符串。
        /// </summary>
        internal static string LisInfo_SampleType {
            get {
                return ResourceManager.GetString("LisInfo_SampleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strSex 的本地化字符串。
        /// </summary>
        internal static string LisInfo_Sex {
            get {
                return ResourceManager.GetString("LisInfo_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock 的本地化字符串。
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男性 的本地化字符串。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message1 的本地化字符串。
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message10 的本地化字符串。
        /// </summary>
        internal static string Message10 {
            get {
                return ResourceManager.GetString("Message10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message11 的本地化字符串。
        /// </summary>
        internal static string Message11 {
            get {
                return ResourceManager.GetString("Message11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message12 的本地化字符串。
        /// </summary>
        internal static string Message12 {
            get {
                return ResourceManager.GetString("Message12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message13 的本地化字符串。
        /// </summary>
        internal static string Message13 {
            get {
                return ResourceManager.GetString("Message13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message14 的本地化字符串。
        /// </summary>
        internal static string Message14 {
            get {
                return ResourceManager.GetString("Message14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message15 的本地化字符串。
        /// </summary>
        internal static string Message15 {
            get {
                return ResourceManager.GetString("Message15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message16 的本地化字符串。
        /// </summary>
        internal static string Message16 {
            get {
                return ResourceManager.GetString("Message16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message17 的本地化字符串。
        /// </summary>
        internal static string Message17 {
            get {
                return ResourceManager.GetString("Message17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message18 的本地化字符串。
        /// </summary>
        internal static string Message18 {
            get {
                return ResourceManager.GetString("Message18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message2 的本地化字符串。
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message3 的本地化字符串。
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message4 的本地化字符串。
        /// </summary>
        internal static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message5 的本地化字符串。
        /// </summary>
        internal static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message6 的本地化字符串。
        /// </summary>
        internal static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message7 的本地化字符串。
        /// </summary>
        internal static string Message7 {
            get {
                return ResourceManager.GetString("Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message8 的本地化字符串。
        /// </summary>
        internal static string Message8 {
            get {
                return ResourceManager.GetString("Message8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message9 的本地化字符串。
        /// </summary>
        internal static string Message9 {
            get {
                return ResourceManager.GetString("Message9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MonitorView_TaskRunning 的本地化字符串。
        /// </summary>
        internal static string MonitorView_TaskRunning {
            get {
                return ResourceManager.GetString("MonitorView_TaskRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MonitorView_TaskStart 的本地化字符串。
        /// </summary>
        internal static string MonitorView_TaskStart {
            get {
                return ResourceManager.GetString("MonitorView_TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string NoSex {
            get {
                return ResourceManager.GetString("NoSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P_Abort 的本地化字符串。
        /// </summary>
        internal static string P_Abort {
            get {
                return ResourceManager.GetString("P_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string P_Cancel {
            get {
                return ResourceManager.GetString("P_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P_Ok 的本地化字符串。
        /// </summary>
        internal static string P_Ok {
            get {
                return ResourceManager.GetString("P_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P_Retry 的本地化字符串。
        /// </summary>
        internal static string P_Retry {
            get {
                return ResourceManager.GetString("P_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rds123 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pdf 的本地化字符串。
        /// </summary>
        internal static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_CheckInstrumentErrorMessage 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_CheckInstrumentErrorMessage {
            get {
                return ResourceManager.GetString("PopupWindow_CheckInstrumentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Message1 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Message1 {
            get {
                return ResourceManager.GetString("PopupWindow_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Message2 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Message2 {
            get {
                return ResourceManager.GetString("PopupWindow_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message3 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Message3 {
            get {
                return ResourceManager.GetString("PopupWindow_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Message4 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Message4 {
            get {
                return ResourceManager.GetString("PopupWindow_Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Message5 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Message5 {
            get {
                return ResourceManager.GetString("PopupWindow_Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Message6 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Message6 {
            get {
                return ResourceManager.GetString("PopupWindow_Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_TaskFinishedMessage 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_TaskFinishedMessage {
            get {
                return ResourceManager.GetString("PopupWindow_TaskFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_About 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_About {
            get {
                return ResourceManager.GetString("PopupWindow_Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_Administrators 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_Administrators {
            get {
                return ResourceManager.GetString("PopupWindow_Title_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_Error 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_Error {
            get {
                return ResourceManager.GetString("PopupWindow_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_MessageBox 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_MessageBox {
            get {
                return ResourceManager.GetString("PopupWindow_Title_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PopupWindow_Title_Wait 的本地化字符串。
        /// </summary>
        internal static string PopupWindow_Title_Wait {
            get {
                return ResourceManager.GetString("PopupWindow_Title_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrecheckView_CheckInstrument 的本地化字符串。
        /// </summary>
        internal static string PrecheckView_CheckInstrument {
            get {
                return ResourceManager.GetString("PrecheckView_CheckInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectInformation 的本地化字符串。
        /// </summary>
        internal static string ProjectInformation {
            get {
                return ResourceManager.GetString("ProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}\Apps\Database\{1}.xls 的本地化字符串。
        /// </summary>
        internal static string PseudoDataFilePath {
            get {
                return ResourceManager.GetString("PseudoDataFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rds 的本地化字符串。
        /// </summary>
        internal static string Rds {
            get {
                return ResourceManager.GetString("Rds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlourReader.exe 的本地化字符串。
        /// </summary>
        internal static string RdsReaderFileName {
            get {
                return ResourceManager.GetString("RdsReaderFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Apps\RdsReader\ 的本地化字符串。
        /// </summary>
        internal static string RdsReaderWorkingDirectory {
            get {
                return ResourceManager.GetString("RdsReaderWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentInformation 的本地化字符串。
        /// </summary>
        internal static string ReagentInformation {
            get {
                return ResourceManager.GetString("ReagentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reagents 的本地化字符串。
        /// </summary>
        internal static string Reagents {
            get {
                return ResourceManager.GetString("Reagents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentSeries 的本地化字符串。
        /// </summary>
        internal static string ReagentSeries {
            get {
                return ResourceManager.GetString("ReagentSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentView1_MB 的本地化字符串。
        /// </summary>
        internal static string ReagentView1_MB {
            get {
                return ResourceManager.GetString("ReagentView1_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentView1_MO 的本地化字符串。
        /// </summary>
        internal static string ReagentView1_MO {
            get {
                return ResourceManager.GetString("ReagentView1_MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentView1_NS 的本地化字符串。
        /// </summary>
        internal static string ReagentView1_NS {
            get {
                return ResourceManager.GetString("ReagentView1_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentView1_UP 的本地化字符串。
        /// </summary>
        internal static string ReagentView1_UP {
            get {
                return ResourceManager.GetString("ReagentView1_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReagentView1_WI 的本地化字符串。
        /// </summary>
        internal static string ReagentView1_WI {
            get {
                return ResourceManager.GetString("ReagentView1_WI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HH:mm:ss 的本地化字符串。
        /// </summary>
        internal static string RemainingTimeFormat {
            get {
                return ResourceManager.GetString("RemainingTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S 的本地化字符串。
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectedReanents 的本地化字符串。
        /// </summary>
        internal static string SelectedReanents {
            get {
                return ResourceManager.GetString("SelectedReanents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        internal static string Separator1 {
            get {
                return ResourceManager.GetString("Separator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 = 的本地化字符串。
        /// </summary>
        internal static string Separator2 {
            get {
                return ResourceManager.GetString("Separator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 : 的本地化字符串。
        /// </summary>
        internal static string Separator3 {
            get {
                return ResourceManager.GetString("Separator3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 的本地化字符串。
        /// </summary>
        internal static string Separator4 {
            get {
                return ResourceManager.GetString("Separator4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _ 的本地化字符串。
        /// </summary>
        internal static string Separator5 {
            get {
                return ResourceManager.GetString("Separator5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 . 的本地化字符串。
        /// </summary>
        internal static string Separator6 {
            get {
                return ResourceManager.GetString("Separator6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos; 的本地化字符串。
        /// </summary>
        internal static string Separator7 {
            get {
                return ResourceManager.GetString("Separator7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; 的本地化字符串。
        /// </summary>
        internal static string Separator8 {
            get {
                return ResourceManager.GetString("Separator8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 | 的本地化字符串。
        /// </summary>
        internal static string Separator9 {
            get {
                return ResourceManager.GetString("Separator9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /RDS;component/Views/MainWindow.xaml 的本地化字符串。
        /// </summary>
        internal static string StartupUri {
            get {
                return ResourceManager.GetString("StartupUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strBeginReadTime 的本地化字符串。
        /// </summary>
        internal static string strBeginReadTime {
            get {
                return ResourceManager.GetString("strBeginReadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strConc 的本地化字符串。
        /// </summary>
        internal static string strConc {
            get {
                return ResourceManager.GetString("strConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        internal static string StringFormat1 {
            get {
                return ResourceManager.GetString("StringFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}{1} 的本地化字符串。
        /// </summary>
        internal static string StringFormat2 {
            get {
                return ResourceManager.GetString("StringFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}{1}{2} 的本地化字符串。
        /// </summary>
        internal static string StringFormat3 {
            get {
                return ResourceManager.GetString("StringFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}{1}{2}{3} 的本地化字符串。
        /// </summary>
        internal static string StringFormat4 {
            get {
                return ResourceManager.GetString("StringFormat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strItemName 的本地化字符串。
        /// </summary>
        internal static string strItemName {
            get {
                return ResourceManager.GetString("strItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strIUperml 的本地化字符串。
        /// </summary>
        internal static string strIUperml {
            get {
                return ResourceManager.GetString("strIUperml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strLogConcResult 的本地化字符串。
        /// </summary>
        internal static string strLogConcResult {
            get {
                return ResourceManager.GetString("strLogConcResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strName 的本地化字符串。
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 strSampleID 的本地化字符串。
        /// </summary>
        internal static string strSampleID {
            get {
                return ResourceManager.GetString("strSampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TaskFinish 的本地化字符串。
        /// </summary>
        internal static string TaskFinish {
            get {
                return ResourceManager.GetString("TaskFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemperatureRange 的本地化字符串。
        /// </summary>
        internal static string TemperatureRange {
            get {
                return ResourceManager.GetString("TemperatureRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 000 的本地化字符串。
        /// </summary>
        internal static string ThreebleZero {
            get {
                return ResourceManager.GetString("ThreebleZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 00:00:00 的本地化字符串。
        /// </summary>
        internal static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TwinkleAnimation 的本地化字符串。
        /// </summary>
        internal static string TwinkleAnimation {
            get {
                return ResourceManager.GetString("TwinkleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App_UnKnow 的本地化字符串。
        /// </summary>
        internal static string UnKnow {
            get {
                return ResourceManager.GetString("UnKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnLock 的本地化字符串。
        /// </summary>
        internal static string UnLock {
            get {
                return ResourceManager.GetString("UnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VaildationError1 的本地化字符串。
        /// </summary>
        internal static string VaildationError1 {
            get {
                return ResourceManager.GetString("VaildationError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VaildationError2 的本地化字符串。
        /// </summary>
        internal static string VaildationError2 {
            get {
                return ResourceManager.GetString("VaildationError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VaildationError3 的本地化字符串。
        /// </summary>
        internal static string VaildationError3 {
            get {
                return ResourceManager.GetString("VaildationError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait 的本地化字符串。
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WathetColor 的本地化字符串。
        /// </summary>
        internal static string WathetColor {
            get {
                return ResourceManager.GetString("WathetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WathetColor2 的本地化字符串。
        /// </summary>
        internal static string WathetColor2 {
            get {
                return ResourceManager.GetString("WathetColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WathetColor3 的本地化字符串。
        /// </summary>
        internal static string WathetColor3 {
            get {
                return ResourceManager.GetString("WathetColor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xml 的本地化字符串。
        /// </summary>
        internal static string Xml {
            get {
                return ResourceManager.GetString("Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
